using System.ComponentModel.DataAnnotations;

namespace API.Web.ApiModels;

// ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
public class PersonaDTO : CreatePersonaDTO
{
  public PersonaDTO(int id, string nombre) : base(nombre)
  {
    Id = id;
  }
  [Key]
  public int Id { get; set; }
}

// Creation DTOs should not include an ID if the ID will be generated by the back end
public abstract class CreatePersonaDTO
{
  protected CreatePersonaDTO(string nombre)
  {
    Nombre = nombre;
  }
  public string Nombre { get; set; }
}
